### ISSUE TITLE
MEM_CLK pin is not assigned

### ISSUE THREAD

**Issue by ztamosevicius** [MinatsuT/CYC1000_SDRAM#1]
MEM_CLK pin is not assigned to the physical pin. This is excerpt from qsf file:
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to MEM_CLK

  When checking pin planer pin B14 is shown as unsigned as well.

**Comment by MinatsuT** [comment]
Thank you for your comment.
The MEM_CLK pin is explicitly assigned to pin B14 by commit 52bc45657edef518b4a55dced9879aa0508f34f0.
